export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const LIKE_COMMENT = 'LIKE_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const LIKE_REPLY = 'LIKE_REPLY';
export const REPLY_TO_COMMENT = 'REPLY_TO_COMMENT';